### ISSUE TITLE
Stopping program

### ISSUE THREAD

**Issue by abeauvisage** [abeauvisage/uasl-image-acquisition#1]
cannot stop program with ctlr-c when camera is not available (cannot open for any reason).

**Comment by HorseBatteryStapleCorrect** [comment]
Did you check in a sort of loop that a SIGINT was issued using the get_signal function ? The goal there is to ignore all signals by default, then it is the responsability of the user to check for the signals using the helper functions in util_signal.hpp. This is to avoid receiving signals in the other threads (since you can't really control where the signal is going)
